; This file was generated by user NIK
; , written 24 Nov 2025 16:06:37
;orc*************
nchnls = 2 
instr 1 
idur = p3; Dauer 
ifreq = p4; Frequenz 
iamp = p5; Lautstaerke 
ich1 = p6; Kanal1 
ich2 = 1-p6; Kanal2 
ifact pow .00125/p3, .6; Steigung 
ifact = (p3 < .0039686 ? .5 : ifact) 
kenv linseg 0, idur*ifact, 1, idur*(1-2*ifact), 1, idur*ifact, 0 
aosc oscili ampdb(iamp)*kenv, ifreq, 1 
outs aosc*ich1, aosc*ich2 
endin 
