package SOUND;
import java.awt.*;
import java.util.*;
import java.io.*;
import java.text.*;

/**
 * This class is used to store a .sco file for CSound. 
 * The input for this class is a vector which contains all the lines we shall write.
 * @version 	$Id$
 * @author 	Nils Kay
 */
public class ScoAccess {

public final static String commentChar=";";
public final static String SCOEXTENSION = ".sco"; 
public final static String ORCEXTENSION = ".orc"; 

    public ScoAccess() {
    }
/**
 * This Method loads the Sco file 
 * @param path which default file to use
 */
public boolean loadSco(String path) {
    String res0, res1;
    File fdes;
    BufferedReader br = null;
    double d;
    int q, ii;

    fdes = new File( path );   
    if (!fdes.exists()) {
	System.out.println("Can not Load motor defaults, File does not exist !");
	return false;
    }
    try {
	br = new BufferedReader(new InputStreamReader(new FileInputStream(fdes)));
    } catch (java.io.FileNotFoundException e) {
	System.out.println("Exception "+e);
	return false;
    }
    try {
	while((res0 = br.readLine()) != null) {
	    if (!(res0.startsWith(commentChar))) { //no comment Line
		q = res0.indexOf('=');
		if (q >= 0) {	// Line with a = char

		    ii = res0.indexOf('\t'); // throw away all after a tab !
		    if (ii <= 0) ii = res0.indexOf('#'); // throw away all after a comment
		    if (ii <= 0) ii = res0.length(); // all of it
		    res1 = res0.substring(q+1,ii);
		    res0 = res0.substring(0,q);
		    // check which parameter this is:
		    if (res0.equals( "UMFANG.G")) {
			//focUmfang = Double.valueOf(res1).doubleValue();
		    }

		}
	    }
	} // end of while
    } // end of try
    catch (java.io.IOException e) {
	System.out.println("loadDef in HandlePar.java : "+e);
	return false;
    }
    return true;
}// end of method

/**
 * This Method saves a sco file
 * @param path wich file to save
 * @param user the name of the user
 */
public boolean saveSco(String path, String user, Vector data) {
    Calendar rightNow;
    double d;
    String wert;
    int n;
    File fdes;
    long millis;
    GregorianCalendar greg = new GregorianCalendar();
    SimpleDateFormat datef = new SimpleDateFormat("dd MMM yyyy HH:mm:ss");
    System.out.println("Try file:"+path);
    millis = new Date().getTime();
    wert = datef.format(new Date(millis)); // actualTime
    fdes = new File( path );   
    n = 0; 	// we use the first of all images in a job as default
    try {
	PrintWriter prs = new PrintWriter(new FileOutputStream(fdes));
	// Headder Information
	prs.println(commentChar+" This file was generated by user "+user);
	prs.println(commentChar+" , written "+ wert);
	//prs.println("MDlocy="+MDlocy+"		# Display y size");
	for (n = 0; n < data.size(); n++) {
	    prs.println((String) data.elementAt(n));
	}
	prs.close();

    }
    catch (java.io.IOException e) {
	System.out.println("SaveJob: "+e );
	return false; 	// Kann File nicht schreiben ! 
    } // End of IO Excep
    //System.out.println("Deflts: saveDefaults was done, FOCUSFOFFSET.F="+focOffset); 
    return true;
}

} // end of class







