# compile Java und C Implementation for GUI
!include ..\makent.sw

SUBDIRS = SOUND Utils

SUBMAKE = $(MAKE) -nologo -f makefile.nt

CLASSFILES= SOUND\*.class Utils\*.class

default: $(SUBDIRS)

# subdir targets:
FRC:
#dummy

$(SUBDIRS) :       FRC
	@cd $@ 
	@echo make: Entering directory `$@' 
	$(SUBMAKE) $(ACTION) 
	@cd ..
	@echo make: Leaving directory `$@' 

jar: 	
	copy SOUND\*.class c:\temp\PHS\Sound
	copy Utils\*.class c:\temp\PHS\Utils
	cd c:\temp\PHS
#c:\jshrink\jshrink.exe .
	jar -cvf jcself_FNS.jar $(CLASSFILES)
	java -cp "C:\Program Files\retroguard-v1.1\retroguard.jar" RetroGuard jcself_FNS.jar jcself.jar Jcself.rgs
	copy jcself.jar l:\MyProjects\PHS\jcself.jar

clean:
	del SOUND\*.class

source: 	
	jar cvf phs_source_108A1.jar make* *.bat Sound\*.java Sound\make* Utils\*.java Utils\makefile* jcself.jar
	move phs_source_108A1.jar Source_backup\phs_source_108A1.jar

